### ISSUE TITLE
Drift detection broken for `slack_conversation.permanent_members`

### ISSUE THREAD

**Issue by fullykubed** [pablovarela/terraform-provider-slack#123]
**Describe the bug**

When `slack_conversation.permanent_members` leave a channel, the provider does not detect and resolve the drift.

**To Reproduce**
1. Setup `slack_conversation` with `permanent_members`
2. Have one of the members leave the channel
3. Run `terraform apply` and notice that the drift isn't detected

**Expected behavior**

Drift is detected and members are re-added to channel if they manually leave.

**Additional context**

`permanent_members` is not updated: https://github.com/pablovarela/terraform-provider-slack/blob/ac2f696c8ecdd301a349f8f7b844e1ceebd8fa25/slack/resource_conversation.go#L293

Thus, the update does not see the drift and does not re-add members: https://github.com/pablovarela/terraform-provider-slack/blob/ac2f696c8ecdd301a349f8f7b844e1ceebd8fa25/slack/resource_conversation.go#L145

**Comment by LanceSandino** [comment]
following.

**Comment by lawliet89** [comment]
Still relevant.

**Comment by LanceSandino** [comment]
bump.

**Comment by LanceSandino** [comment]
Bump

**Comment by pablovarela** [comment]
Apologies for the delay. I will take a look at this next week

**Comment by LanceSandino** [comment]
bump :)

**Comment by LanceSandino** [comment]
Bump again so it's not forgotten about

**Comment by LanceSandino** [comment]
Still waiting on this.

**Comment by lawliet89** [comment]
Not stale.
