### ISSUE TITLE
Needs a 1.2 release

### ISSUE THREAD

**Issue by llamahunter** [pablovarela/terraform-provider-slack#142]
**Is your feature request related to a problem? Please describe.**
Several non patch based features have been added to the provider, but the minor version has not been incremented

**Describe the solution you'd like**
Release new features in minor version updates, not patch version updates (which should be for bug fixes, not api additions)

**Additional context**
I would like to put version constraints on the provider using the `~>` operator to make sure the version is use meets some minimum version, but prevent unexpected major version changes that might break the api. Currently, I need later than version 1.1.24, but putting `~> 1.1.24` would prevent a minor version update in the future to `1.2` which, per SemVer, should _not_ break the existing api compatibility. I only want to prevent updates to `2.x` which _could_ break backwards compatibility of the api, e.g. by using `~> 1.2`

**Comment by pablovarela** [comment]
Noted. I will increase the minor version for future changes that add functionality.
