### ISSUE TITLE
Error: couldn't set conversation purpose "": not_in_channel

### ISSUE THREAD

**Issue by wscourge** [pablovarela/terraform-provider-slack#161]
**Describe the bug**
The following: 

```
# tzif.io
resource "slack_conversation" "log-tzif" {
  name    = "log-tzif"
  purpose = "Automated monitoring of tzif organization-level events"
  adopt_existing_channel = true
  is_private = false
}
```

Produces this error:

> 
> │ Error: couldn't set conversation purpose Automated monitoring of tzif organization-level events: not_in_channel
> │
> │   with slack_conversation.log-tzif,
> │   on slack.tf line 2, in resource "slack_conversation" "log-tzif":
> │    2: resource "slack_conversation" "log-tzif" {

**Expected behavior**

No error

**Screenshots**
### Bot token scopes
<img width="674" alt="image" src="https://user-images.githubusercontent.com/16985871/202153455-7e59c394-4da4-42fb-a2aa-1ae495ad6bdf.png">

### Error
![image](https://user-images.githubusercontent.com/16985871/202153273-5ef8b44e-20df-4c6d-85de-ec76e44c9e77.png)

**Comment by smoya** [comment]
We are being hit by this, even though we are using user tokens:

![image](https://github.com/pablovarela/terraform-provider-slack/assets/1083296/7f6e7759-9efe-4a33-a7c1-6c5b4138090f)

Any idea what could be the issue here @pablovarela @wscourge 

Thanks

**Comment by smoya** [comment]
Is inviting the bot app on all managed channels the solution? Can't the provider automate somehow this by joining the channel if fails? 🤔
