### ISSUE TITLE
[slack_conversation] [adopt_existing_channel] Channel not found if archived

### ISSUE THREAD

**Issue by ylorenzati** [pablovarela/terraform-provider-slack#192]
**Describe the bug**
Hello, when trying to create a Slack channel with adopt_existing_channel = true
the code fail if a channel already exist and is archived

I believe it's because of this [line](https://github.com/pablovarela/terraform-provider-slack/blame/master/slack/resource_conversation.go#L200)
Introduce in [this](https://github.com/pablovarela/terraform-provider-slack/pull/162/files) pull request

If you can just confirm my understanding is correct, I will happily provide a pr to fix the issue

ps: I think the code is clear enough to not provide reproduce steps, but if you disagree I can provide some code

**Comment by JensErat** [comment]
Also observed this. We fixed this by manually deleting the channels from state, but probably also using `action_on_destroy: none` should have worked.
