### ISSUE TITLE
(feat) `slack_users` data call

### ISSUE THREAD

**Issue by fishpen0** [pablovarela/terraform-provider-slack#204]
**Is your feature request related to a problem? Please describe.**
Similar to `slack_user` data call but loads all slack users at once into a map.  The objective here is to reduce the likelihood of being rate limited by the slack API when loading all slack users at once.

**Describe the solution you'd like**
`slack_users` data call loads all slack users into a map with name, ID, and email for further processing

**Describe alternatives you've considered**
```
data "slack_user" "by_email" {
  # flatten the grouplist to just emails becasue the groups have duplicate emails
  for_each = { for user in local.grouplist : user.email_address => user... }
  email    = each.key
}
```
This is rate limited almost immediately by the slack API as the number of users is ~>100

* An alternative would be to implement a purposeful rate limit into the existing provider somehow to stop terraform from bombing out
* A different alternative would be to update `slack_usergroup` to accept email addresses as an alternative in the `users` list

**Comment by tasansga** [comment]
I'm hitting the rate limit fairly often as well.

The [GitHub terraform provider](https://registry.terraform.io/providers/integrations/github/latest/docs) configuration block offers the following attributes for a similar problem:
![image](https://github.com/pablovarela/terraform-provider-slack/assets/22353635/bbf1d576-1ec4-4131-98e6-063e1c33b099)

**Comment by fishpen0** [comment]
Pagerduty has a similar call to fetch all users that prevents us from hitting rate issues: https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/data-sources/users
