### ISSUE TITLE
Rename slack_converasion to slack_channel resource

### ISSUE THREAD

**Issue by dimisjim** [pablovarela/terraform-provider-slack#35]
I think it would make more sense.

I though that it can also manage a private direct chat conversation, but it seems that this is not the case: https://registry.terraform.io/providers/pablovarela/slack/latest/docs/resources/conversation which makes the naming even more confusing.

What do you think?

**Comment by pablovarela** [comment]
Slack has deprecated the `channels` API. See: [channels.create](https://api.slack.com/methods/channels.create). `slack_conversation` resource is using [conversations.create](https://api.slack.com/methods/conversations.create) behind the scenes so `conversations` seems more appropriate than `channel`.

The Slack SDK is not very consistent with the deprecation. Methods to manage conversations still return Channel objects which are marked as deprecated. But it looks like the general direction is to get rid of channels in favour of conversations.

It should be possible to write a resource to open or resume direct messages using [conversations.open](https://api.slack.com/methods/conversations.open). How are you planning to use it? How would the resource looks like?

**Comment by dimisjim** [comment]
Thanks for the quick response,

I am not planning to manage private direct conversations.
The issue was opened because the naming of the channel resource seemed weird to me, but now it makes more sense that you explained it :+1: 

I'll close this issue.
