### ISSUE TITLE
Create a new slack_user resource or refactor the existing datasource into a resource

### ISSUE THREAD

**Issue by dimisjim** [pablovarela/terraform-provider-slack#36]
It seems more useful to have this as a managed resource than a datasource which is only supposed to fetch data, not manage anything.

**Comment by pablovarela** [comment]
Looking at the [Slack API](https://api.slack.com/methods) it does not seem to be a way to create users. If you know a way to do it I will look into it.

When I wrote this provider my use case was quite simple: create a slack channel and add existing users to it.

I am happy to add resources or data sources that do not require a premium account as i don't have access to one at the moment. Or if you feel like submitting a PR that would be be great.

**Comment by dimisjim** [comment]
I see, the `admins` suite of API methods is only available for the the "Enterprise Grid" plan: https://api.slack.com/admins

Will close this issue then.
