### ISSUE TITLE
Documentation missing specifics on Slack Token OAuth Scopes

### ISSUE THREAD

**Issue by gregoryfischer** [pablovarela/terraform-provider-slack#43]
The documentation does not specify which OAuth Bot Scopes are required for the this provider to perform all its tasks. Could that be added to the documentation?

**Comment by gregoryfischer** [comment]
Thanks, the documentation updates in v1.1.3 fills the gap nicely.

**Comment by pablovarela** [comment]
no problem. I really didn't feel like documenting but now it's done I am happy I did.
