### ISSUE TITLE
Feature Request: Add support for Slack usergroups

### ISSUE THREAD

**Issue by gregoryfischer** [pablovarela/terraform-provider-slack#48]
Currently, my testing shows permanent_members only accepts a list of user ids, but slack now supports inviting usergroups to slack conversations/channel. Adding support for usergroups would eliminate the need for passing an array of user names to the datasource which for large organizations can get quite unwieldy.

**Comment by gregoryfischer** [comment]
Yes, I too tested passing group ids to this providers slack_conversation resource and got the expected error. I was not sure if this was exposed somehow in the go-slack source. I do know the primary feature I was hoping for was indeed adding users via group id invites so long lists of users in a data file did not need to be maintained and only groups.

My org only supports bot OAuth tokens and is restricted to a specific workspace, so yes, I also do not have access to `admin` scopes.

What is exposed to bot OAuth tokens is usergroups:read and usergroups:write and I think I would put a few new `usergroups` resources to good use to manage group memberships.

`
resource "slack_user_group" "test_group" {
  name        = "my-new-usergroup"
  handle      = "my_new_usergroup"
  description = "My description"
  channels    = ["ABC123", "321CBA"]
}
`

I could be wrong but I think these scopes and usergroups are relatively new. https://api.slack.com/scopes/usergroups:write

**Comment by gregoryfischer** [comment]
BTW, knowing which Bot OAuth scopes I needed to get started was a bit of trial and error which is why I logged this request as well. https://github.com/pablovarela/terraform-provider-slack/issues/43

**Comment by pablovarela** [comment]
> Yes, I too tested passing group� ids to this providers slack_conversation resource and got the expected error. I was not sure if this was exposed somehow in the go-slack source. I do know the primary feature I was hoping for was indeed adding users via group id invites so long lists of users in a data file did not need to be maintained and only groups.
> 
> My org only supports bot OAuth tokens and is restricted to a specific workspace, so yes, I also do not have access to `admin` scopes.
> 
> What is exposed to bot OAuth tokens is usergroups:read and usergroups:write and I think I would put a few new `usergroups` resources to good use to manage group memberships.
> 
> ```
> resource "slack_user_group" "test_group" {
>   name        = "my-new-usergroup"
>   handle      = "my_new_usergroup"
>   description = "My description"
>   channels    = ["ABC123", "321CBA"]
> }
> ```
> 
> I could be wrong but I think these scopes and usergroups are relatively new. https://api.slack.com/scopes/usergroups:write

ok, I will look into creating a new a resource and probably a data source for `usergroups` then. I think it is going to be the cleanest solution.

**Comment by pablovarela** [comment]
> BTW, knowing which Bot OAuth scopes I needed to get started was a bit of trial and error which is why I logged this request as well. #43

Sorry about that. Instead of listing the scopes directly in the documentation I think I will link the documentation for API methods use by each resource. That is so I do not have to update the docs if the scopes change. I may end up doing both listing the scopes that are required at the moment of writing the documentation, plus links to the API methods used to double check in case they are not enough.

**Comment by pablovarela** [comment]
I've just released [v1.1.0](https://github.com/pablovarela/terraform-provider-slack/releases/tag/v1.1.0) which includes this feature. There is available documentation for the [resource](https://registry.terraform.io/providers/pablovarela/slack/latest/docs/resources/usergroup) and the [data source](
https://registry.terraform.io/providers/pablovarela/slack/latest/docs/data-sources/usergroup).

Please let me know if you have any questions.

**Comment by gregoryfischer** [comment]
> I've just released [v1.1.0](https://github.com/pablovarela/terraform-provider-slack/releases/tag/v1.1.0) which includes this feature. There is available documentation for the [resource](https://registry.terraform.io/providers/pablovarela/slack/latest/docs/resources/usergroup) and the [data source](https://registry.terraform.io/providers/pablovarela/slack/latest/docs/data-sources/usergroup).
> 
> Please let me know if you have any questions.

Thanks. I look forward to giving it a try.
