### ISSUE TITLE
Feature request: add terraform import to provider

### ISSUE THREAD

**Issue by fralvarop** [pablovarela/terraform-provider-slack#55]

**Comment by pablovarela** [comment]
It is not documented by `import` should work for most if not all resources. For example to import a conversation you can run `terraform import ADDRESS CHANNEL_ID`. 

I will update the documentation to include the `terraform import` usage.

**Comment by fralvarop** [comment]
I tried that before open the issue, no luck same error with the 3 options below

```
terraform import 'module.root.module.slack[0].slack_conversation.squad' "G01E9JL38JD"
terraform import 'module.root.module.slack[0].slack_conversation.squad' "client/T4MRXEJD6/G01E9JL38JD"
terraform import 'module.root.module.slack[0].slack_conversation.squad' "T4MRXEJD6/G01E9JL38JD"

Error: Invalid provider configuration
```

**Comment by pablovarela** [comment]
did you set `SLACK_TOKEN` ?

**Comment by fralvarop** [comment]
Yes sir, is set.

```
provider "slack" {
  token = local.secrets["providers"]["slack"]["api_key"]
}
```

**Comment by pablovarela** [comment]
I've just tested the import and it works for me. Could you try these two things:

1. Remove the token configuration from the provider and set the env variable `SLACK_TOKEN` instead. Try to import
2. Hardcoding the token in the provider

Both of those work me. There are also automated tests for importing resources so I am quite confident it works. We'll get to the bottom of this.

**Comment by fralvarop** [comment]
> I've just tested the import and it works for me. Could you try these two things:
> 
> 1. Remove the token configuration from the provider and set the env variable `SLACK_TOKEN` instead. Try to import
> 2. Hardcoding the token in the provider
> 
> Both of those work me. There are also automated tests for importing resources so I am quite confident it works. We'll get to the bottom of this.

So hardcoding the token did the import half work. But I get this warning
```
Warning: channel with ID G01E9JL38JD not found
```

The channel does exist and that's his ID.

**Comment by fralvarop** [comment]
I can't see the channel I need through the token I have. So I guess this can be close.

Thank you so much for your help! :)

**Comment by pablovarela** [comment]
No problem! I was about to suggest to check you can see the channel with that token using: https://api.slack.com/methods/conversations.info/testhttps://api.slack.com/methods/conversations.info/test.

FYI I am just created a https://github.com/pablovarela/terraform-provider-slack/pull/56 update the docs. I will merge it as soon as I make the linters happy.
