### ISSUE TITLE
Show which user was queried when `users_not_found` returned by data source

### ISSUE THREAD

**Issue by edify42** [pablovarela/terraform-provider-slack#69]
Hi @pablovarela !

We use the datasource like below for a number of users who signin via SSO and we maintain a list of them with terraform that can do other things like below:

```hcl
data "slack_user" "by_email" {
  for_each = toset(flatten([
    [var.users_in_teams["team_x"]],
    [var.users_in_teams["team_y"]],
    [var.users_in_teams["team_z"]],
    [var.users_in_teams["team_a"]],
    [var.users_in_teams["team_b"]]
  ]))
  email = each.key
}
```

Sometimes people leave our org and their email is no longer valid in slack. The provider currently returns the below:
```
Error: users_not_found

  on users-slack-info.tf line 1, in data "slack_user" "by_email":
   1: data "slack_user" "by_email" {

```
Without the detail into which user left. making it hard for us to figure it out quickly. I can make a PR to output which user it was that left (either their name or email)

**Comment by pablovarela** [comment]
Implemented by https://github.com/pablovarela/terraform-provider-slack/pull/70

**Comment by edify42** [comment]
Thanks mate :heart:

```bash

Error: not found fake-user@gmail.com: users_not_found

  on users-slack-info.tf line 1, in data "slack_user" "by_email":
   1: data "slack_user" "by_email" {


```
