### ISSUE TITLE
feature  request: action_on_destroy for conversation resouses

### ISSUE THREAD

**Issue by qxmips** [pablovarela/terraform-provider-slack#79]
In many organizations only slack admins can archive a channel,  hence having an app token I can successfully create a  channel but terraform code fails on channel deletion. Would it make sense to add 'action_on_destroy' parameter to the conversation resource (like it's done in  [here](https://github.com/jmatsu/terraform-provider-slack) )? 

This would really help in using the provider in our project.
I can create a [pull request ](https://github.com/qxmips/terraform-provider-slack/tree/feature/action_on_destroy) if it would be acceptable to go with that option.

**Comment by pablovarela** [comment]
I think this makes sense for people that can not get admin tokens. A PR for it is more than welcome!

I have one question though. If you set `action_on_destroy=false` then the channels does not get archived which means that you can not reuse the channel name, and that you will leave channels behind. Isn't that a problem for you? I guess as far as we document it properly it should be ok. 

I took a look at your change. Some preliminary notes:

- I would make `action_on_destroy` an optional parameter with default behaviour `archive`. That is to make it backwards compatible with the current implementation.
- The [documentation](https://github.com/pablovarela/terraform-provider-slack/blob/master/docs/resources/conversation.md) needs to be updated.
- We have tests for [archiving/unarchiving channels](https://github.com/pablovarela/terraform-provider-slack/blob/master/slack/resource_conversation_test.go#L75); this new feature should be tested as well. I can help writing the tests if necessary.

**Comment by qxmips** [comment]
@pablovarela thank you, for the prompt response, yes, leaving a channel behind would fail the second run with the same channel name, but we can live with that. 

I've [updated](https://github.com/qxmips/terraform-provider-slack/tree/feature/action_on_destroy) the documentation and made `action_on_destroy` to be an optional parameter that  defaults to `archive` but I need some help with writing the tests, cause I am a newbie in golang.

**Comment by qxmips** [comment]
sent a pr without testing part.

**Comment by pablovarela** [comment]
I commented on the PR. Don't worry about the tests. The default behaviour is tested by the current tests and that is what could break existing integrations. I will add the tests for the new option once we merge your PR, and I have some time to do it.

Thanks again for your contribution!
