### ISSUE TITLE
Enhancement - Creation Incoming WebHooks

### ISSUE THREAD

**Issue by evgeniyy2003** [pablovarela/terraform-provider-slack#85]
Hi,
It will be good to add creation Incoming WebHooks

Thanks in advance,
Evgeniy

**Comment by pablovarela** [comment]
I don't think it is possible to create Incoming WebHooks via the [Web API](https://api.slack.com/methods). If you find a way please let me know and I will happily add support for it.

**Comment by evgeniyy2003** [comment]
I'm not sure,
But maybe this can help
https://api.slack.com/messaging/webhooks#incoming_webhooks_programmatic

**Comment by pablovarela** [comment]
Thanks for link. Unfortunately it doesn't help, that method is to generate an Incoming Webhook to a channel selected by the user when they install it your Slack app in a workspace.

**Comment by dafelipe130** [comment]
As far as I can tell, Slack is planning to replace webhooks with Apps. Is there a roadmap for that instead?

**Comment by evgeniyy2003** [comment]
Thanks,
Yes, when Slack stops supporting the incoming webhook, all webhook integration will also be replaced. 
I hope the Apps API will provide more functionality for integration.

**Comment by evgeniyy2003** [comment]
I've checked this. It's just moves the webhook url to the Apps module. 
The sending messages to channels remains the same. 
Based on this [](https://github.com/slackapi/template-channel-webhooks) , this is now automated with member_joined_channel.
But does not provide the required solution
