### ISSUE TITLE
Managing users

### ISSUE THREAD

**Issue by redzioch** [pablovarela/terraform-provider-slack#87]
Is it difficult to add users management, i.e. inviting/removing from workspace?

**Comment by pablovarela** [comment]
All supported operations are documented here: https://registry.terraform.io/providers/pablovarela/slack/latest/docs

inviting/removing users is not currently supported. Terraform is all about describing the desired state and applying CRUD operations to achieve it. Inviting a user requires an external action which does not really fit the model as it is not really user creation and the usr resource can not be used until the invitation is accepted, if it is accepted. As creation is not possible, then removing is not implemented either. I hope this makes sense.
